#!/usr/bin/env python3
"""INFRANEX GPU research — final PDF report (ReportLab body; cover merged via pypdf)."""
import json
import os
import sys
import hashlib

PDF_SKILL_SCRIPTS = "/home/z/my-project/skills/pdf/scripts"
if PDF_SKILL_SCRIPTS not in sys.path:
    sys.path.insert(0, PDF_SKILL_SCRIPTS)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    Image, KeepTogether, CondPageBreak, HRFlowable,
)
from reportlab.platypus.tableofcontents import TableOfContents
from PIL import Image as PILImage

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#504933')
COVER_BLOCK   = colors.HexColor('#867b5a')
BORDER        = colors.HexColor('#cfcab8')
ICON          = colors.HexColor('#8c7e52')
ACCENT        = colors.HexColor('#87702a')
ACCENT_2      = colors.HexColor('#3a95b4')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ---------- fonts ----------
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ---------- data ----------
DIR = "/home/z/my-project/scripts/gpu-research"
rank = json.load(open(f"{DIR}/rankings.json"))
evid = json.load(open(f"{DIR}/subnet-evidence.json"))
dset = json.load(open(f"{DIR}/dataset.json"))
taostat = list(json.load(open(f"{DIR}/taostat-subnets.json")).values())
stats = rank["stats"]
viewA = rank["viewA"]
viewB = rank["viewB"]["classes"]
viewC = rank["viewC"]
TAO_P = stats["taoPriceUsd"]

def usd_mo(tao_per_day):
    return (tao_per_day or 0) * TAO_P * 30

def esc(s):
    return (s or "").replace("&", "&").replace("<", "<").replace(">", ">")

def short(s, n):
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"

# unresolved-coverage by emissions
unresolved = [s for s in evid if s["readmeStatus"] != "ok"]
unres_em = sum(s["minerEmissionTaoPerDay"] or 0 for s in unresolved)
total_miner_em = stats["totalMinerTaoPerDay"]
unres_share = 100 * unres_em / total_miner_em if total_miner_em else 0
sn122 = next(s for s in evid if s["netuid"] == 122)
sn64 = next(s for s in evid if s["netuid"] == 64)
sn90 = next(s for s in evid if s["netuid"] == 90)

by_netuid = {s["netuid"]: s for s in evid}
gpu_of = lambda uid: ", ".join(g["gpu"].replace("NVIDIA ", "") for g in by_netuid[uid]["gpus"])

# ---------- document ----------
OUT_BODY = f"{DIR}/report-body.pdf"
MARGIN = 0.85 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
DOC_TITLE = "Which GPUs Mine Bittensor? Subnet GPU Requirements Research"

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def on_page(canvas, doc):
    canvas.saveState()
    # header: muted title + accent rule
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # footer: author left, page number right, light rule above
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.6)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, "INFRANEX BT - DevOps Intelligence")
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(doc.page))
    canvas.restoreState()

doc = TocDocTemplate(
    OUT_BODY, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author="Z.ai", creator="Z.ai",
    subject="GPU requirements across Bittensor subnets, mined from subnet repositories",
)

# ---------- styles ----------
S = {}
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=21, leading=26,
                         textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14.5, leading=19,
                         textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                           textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=9)
S['bullet'] = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=16,
                             textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                             leftIndent=16, bulletIndent=4, spaceAfter=5)
S['quote'] = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10, leading=15,
                            textColor=TEXT_MUTED, leftIndent=24, spaceBefore=4, spaceAfter=8)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                              textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=3, spaceAfter=6)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=20, leading=26,
                                textColor=TEXT_PRIMARY, spaceAfter=14)
S['th'] = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9, leading=12,
                         textColor=TABLE_HEADER_TEXT, alignment=TA_LEFT)
S['td'] = ParagraphStyle('TD', fontName='FreeSerif', fontSize=8.8, leading=12,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['td_small'] = ParagraphStyle('TDS', fontName='FreeSerif', fontSize=7.8, leading=10.5,
                               textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['td_num'] = ParagraphStyle('TDN', fontName='FreeSerif', fontSize=8.8, leading=12,
                             textColor=TEXT_PRIMARY, alignment=TA_CENTER)
S['stat_big'] = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=20, leading=24,
                               textColor=ACCENT, alignment=TA_CENTER)
S['stat_lbl'] = ParagraphStyle('StatLbl', fontName='FreeSerif', fontSize=8, leading=11,
                               textColor=TEXT_MUTED, alignment=TA_CENTER)

story = []

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

H1_THRESHOLD = AVAIL_H * 0.25

def h1(num, title, first_para):
    """Chapter heading + accent rule + first paragraph, orphan-protected."""
    head = add_heading(f"{num}.  {title}", S['h1'], level=0)
    rule = HRFlowable(width="100%", color=ACCENT, thickness=1.6, spaceBefore=0, spaceAfter=10)
    return [CondPageBreak(H1_THRESHOLD), KeepTogether([head, rule, first_para])]

def h2(text):
    return Paragraph(f"<b>{text}</b>", S['h2'])

def body(text):
    return Paragraph(text, S['body'])

def embed_image(path, max_width=None, max_height=None):
    if max_width is None:
        max_width = AVAIL_W
    if max_height is None:
        max_height = A4[1] * 0.35
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow if ow > max_width else 1.0,
                max_height / oh if oh > max_height else 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)

def chart_block(path, max_height=270):
    return [Spacer(1, 14), embed_image(path, max_height=max_height), Spacer(1, 14)]

def callout_row(items):
    """Row of stat callout boxes. items = [(value, label), ...]"""
    n = len(items)
    gap = 10
    w = (AVAIL_W - gap * (n - 1)) / n
    cells = []
    for val, lbl in items:
        inner = Table(
            [[Paragraph(f"<b>{val}</b>", S['stat_big'])], [Paragraph(lbl, S['stat_lbl'])]],
            colWidths=[w - 2],
        )
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 0.8, BORDER),
            ('TOPPADDING', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, -1), (-1, -1), 9),
            ('TOPPADDING', (0, -1), (-1, -1), 1),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        cells.append(inner)
    outer = Table([cells], colWidths=[w] * n, hAlign='CENTER')
    outer.setStyle(TableStyle([
        ('LEFTPADDING', (0, 0), (-1, -1), 0 if n == 1 else gap // 2),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0 if n == 1 else gap // 2),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return outer

def make_table(header, rows, ratios, small=False, num_cols=()):
    cell = S['td_small'] if small else S['td']
    td_num = S['td_num'] if not small else ParagraphStyle('TDNS', parent=S['td_num'], fontSize=7.8, leading=10.5)
    data = [[Paragraph(f"<b>{esc(h)}</b>", S['th']) for h in header]]
    for r in rows:
        row = []
        for i, c in enumerate(r):
            if isinstance(c, Paragraph):
                row.append(c)
            else:
                st = td_num if i in num_cols else cell
                row.append(Paragraph(esc(str(c)), st))
        data.append(row)
    widths = [ratio * AVAIL_W for ratio in ratios]
    assert sum(widths) <= AVAIL_W + 0.5, f"table too wide: {sum(widths):.1f} > {AVAIL_W:.1f}"
    t = Table(data, colWidths=widths, repeatRows=1, hAlign='CENTER')
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    return t

# =====================================================================
# TABLE OF CONTENTS
# =====================================================================
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5, leading=20, leftIndent=6),
]
story.append(Paragraph("<b>Table of Contents</b>", S['toc_title']))
story.append(HRFlowable(width="100%", color=ACCENT, thickness=1.6, spaceAfter=12))
story.append(toc)
story.append(Spacer(1, 30))
story.append(h2("About this snapshot"))
story.append(body(
    "This study was produced by the INFRANEX BT DevOps intelligence pipeline as a repo-level audit "
    "of GPU requirements across the entire Bittensor subnet registry. Every claim in the chapters "
    "that follow is anchored to a verbatim quote from a subnet repository - README files, "
    "min_compute.yml hardware declarations, Docker files and dependency manifests fetched at "
    f"snapshot block {dset['blockNumber']:,} on September 10, 2026, with TAO priced at ${TAO_P:.2f}. "
    "Chapters 3 and 4 rank GPUs by verified evidence and by VRAM class, Chapter 5 cross-checks the "
    "findings against two independent classification systems, Chapter 6 reproduces the full evidence "
    "trail, and Chapters 7-8 translate the data into hardware strategy and its limits. The raw JSON "
    "datasets (per-subnet evidence and aggregate rankings) accompany this document for independent "
    "verification."))
story.append(PageBreak())

# =====================================================================
# 1. EXECUTIVE SUMMARY
# =====================================================================
a100 = next(v for v in viewA if v["gpu"] == "NVIDIA A100")
r4090 = next(v for v in viewA if v["gpu"] == "NVIDIA RTX 4090")
h200 = next(v for v in viewA if v["gpu"] == "NVIDIA H200")
h100 = next(v for v in viewA if v["gpu"] == "NVIDIA H100")
cls24 = next(c for c in viewB if "24 GB" in c["class"])
cls812 = next(c for c in viewB if "8-12" in c["class"] or "8\u201312" in c["class"])

story.extend(h1(1, "Executive Summary", body(
    "This report answers a direct question with repo-level evidence: across all "
    f"{stats['totalSubnets']} live Bittensor subnets, which GPU is mostly used or required for "
    "mining - the H200, the RTX 4090, or something else? We scanned the GitHub repositories "
    "linked on-chain for every subnet, pulled each repository's README, its min_compute.yml "
    "hardware declaration where one exists, and its Docker and dependency files, then extracted "
    "every named GPU model together with the context in which it appears. In total, "
    f"{stats['readmeOk']} READMEs ({round(100 * stats['readmeOk'] / stats['totalSubnets'])}% of all subnets) "
    f"and {stats['withMinCompute']} structured min_compute.yml specs were analyzed at snapshot block "
    f"{dset['blockNumber']:,} with TAO trading at ${TAO_P:.2f}.")))

story.append(body(
    "The headline finding is that <b>no single GPU model dominates, but the RTX 4090's 24 GB class "
    "is the center of gravity for individual GPU miners</b>, while the A100 is the most frequently "
    "named card overall and H100/H200-class datacenter GPUs dominate the highest-paying niches. "
    f"The A100 appears in {a100['anyCount']} subnet repositories (with {a100['reqCount']} explicit miner-side "
    f"requirements, representing {a100['reqTaoPerDay']:.0f} TAO/day of miner-side emissions). "
    f"The RTX 4090 is explicitly named by {r4090['anyCount']} repositories ({r4090['reqCount']} as a hard "
    "miner requirement), and several of the most profitable consumer-GPU subnets publish the 4090 "
    "as their reference card. The H200, by contrast, is a niche card in Bittensor mining today: "
    f"only {h200['anyCount']} repositories mention it at all, and its single hard requirement "
    "(SN90 KubeTEE) bundles it inside an H100/H200/B200 cluster specification."))

story.append(Spacer(1, 6))
story.append(callout_row([
    ("A100", f"Most-named GPU - {a100['anyCount']} repos, {a100['reqCount']} hard requirements"),
    ("RTX 4090", f"Top consumer GPU - {cls24['subnets']} subnets in its 24 GB class"),
    ("H200", f"Niche - only {h200['anyCount']} repos mention it"),
]))
story.append(Spacer(1, 12))

story.append(body(
    "Measured by reward pool rather than by repository count, the 24 GB class is where the money "
    f"is: subnets whose explicit minimum fits a 24 GB card (RTX 4090 / 3090 / 5090 class) carry "
    f"{cls24['taoPerDay']:.0f} TAO/day of miner-side emissions - about ${usd_mo(cls24['taoPerDay']):,.0f} per month at current "
    f"prices - the largest single VRAM bucket in the network. The broad 8-12 GB bucket hosts more "
    f"subnets ({cls812['subnets']}) but only {cls812['taoPerDay']:.0f} TAO/day in rewards. The 80 GB+ bucket "
    "(A100 80G / H100 / H200) spans "
    f"{viewB[-1]['subnets']} subnets and {viewB[-1]['taoPerDay']:.0f} TAO/day, concentrated almost entirely in "
    "inference-marketplace and TEE-cluster subnets that rent rather than buy their GPUs. For a solo "
    "miner deciding what hardware to acquire, the practical answer is therefore: a 24 GB RTX 4090 "
    "remains the most versatile mining card in the Bittensor ecosystem, with an A100/H100 rental "
    "strategy as the high-end alternative, and the H200 specifically NOT worth acquiring for "
    "Bittensor mining alone at this time."))

sum_rows = []
for v in viewA[:8]:
    sum_rows.append([
        v["gpu"].replace("NVIDIA ", ""),
        f"{v['reqCount']} req / {v['supportedCount']} sup / {v['anyCount']} named",
        f"{v['reqTaoPerDay']:.1f}",
        f"${usd_mo(v['reqTaoPerDay']):,.0f}",
    ])
story.append(Spacer(1, 8))
story.append(make_table(
    ["GPU model", "Subnets (required / supported / named)", "Miner-side TAO/day behind requirements", "USD/month equivalent"],
    sum_rows, [0.26, 0.34, 0.24, 0.16], num_cols=(1, 2, 3)))
story.append(Spacer(1, 4))
story.append(Paragraph("Table 1: Tiered GPU ranking from repository evidence. 'Required' = explicit miner-side "
                       "requirement; 'supported' = miner-side declared/accepted; 'named' = any mention. "
                       "Emissions are miner-side TAO/day at snapshot.", S['caption']))
story.append(Spacer(1, 6))

# =====================================================================
# 2. METHODOLOGY AND DATA SOURCES
# =====================================================================
story.extend(h1(2, "Methodology and Data Sources", body(
    "The analysis pipeline ran in four stages. First, we pulled the live subnet registry from the "
    "Finney chain through the INFRANEX BT platform's network API at block "
    f"{dset['blockNumber']:,}, capturing {stats['totalSubnets']} subnets with their names, per-subnet emissions "
    f"and on-chain identity links: {stats['withGithub']} of the {stats['totalSubnets']} subnets publish a GitHub URL in their "
    "chain identity, and 7 more were recovered through the platform's curated override registry. "
    "Second, we fetched each repository's README (trying main and master branches across six common "
    "README filenames), plus requirements.txt, pyproject.toml, setup.py, Dockerfile, docker-compose "
    "and .env templates, and - critically - min_compute.yml, the Bittensor convention file through "
    f"which teams declare minimum compute per role. {stats['readmeOk']} repositories yielded a usable README and "
    f"{stats['withMinCompute']} shipped a min_compute.yml.")))

story.append(body(
    "Third, we ran a catalog-based extractor over every text artifact: 30+ canonical GPU patterns "
    "(H200, H100, A100, RTX 4090, L40S, A6000, B200 and so on, including variants such as RTX 4090D, "
    "4070 Ti SUPER and MI300X), VRAM minimums ('at least 24 GB', 'min_vram: 80'), and the structured "
    "compute_spec.miner.gpu / compute_spec.validator.gpu blocks of min_compute.yml. Every mention was "
    "classified into three evidence tiers: <b>tier 1 - explicit miner-side requirement</b> (requirement "
    "language or a min_compute.yml miner block), <b>tier 2 - miner-side supported/declared</b> (mentioned "
    "as accepted or declared hardware in a mining context) and <b>tier 3 - generic mention</b> "
    "(benchmark tables, validator documentation, pricing examples). Fourth, all findings were "
    "cross-checked against two independent signals: the taostat community registry's hw_requirements "
    "field and the INFRANEX requirements profiler that already powers the platform's DevOps engine."))

story.append(body(
    "Two important coverage caveats frame everything that follows. First, "
    f"{len(unresolved)} of {stats['totalSubnets']} subnets have no readable repository README (they are parked, "
    "deprecated, renamed or publish no public code), which removes "
    f"{unres_share:.0f}% of miner-side emissions from direct observation; the largest gaps are SN0 (the root "
    "network, which is not a minable subnet), SN120 Affine, SN95 Actual and SN97 Albedo, all of which "
    "exist but expose no README today. Second, many teams document hardware on external docs sites or "
    "in private miner onboarding repos rather than in the public repository, so repo evidence is a "
    "floor, not a ceiling: subnets with no GPU mention include some that verifiably require GPUs "
    "and are classified by INFRANEX's profiler instead."))

meth_rows = [
    ["Subnets in live registry", f"{stats['totalSubnets']}", "Finney chain snapshot, block " + f"{dset['blockNumber']:,}"],
    ["Subnets with on-chain GitHub link", f"{stats['withGithub']}", "Chain identity registry"],
    ["READMEs successfully analyzed", f"{stats['readmeOk']} ({round(100 * stats['readmeOk'] / stats['totalSubnets'])}%)", "raw.githubusercontent.com, 6 filename variants x 2 branches"],
    ["min_compute.yml specs found", f"{stats['withMinCompute']}", "Root + miners/ + docs/ paths"],
    ["Subnets naming a specific GPU model", f"{stats['withGpuMention']}", "Catalog of 30+ canonical GPU patterns"],
    ["Subnets with explicit VRAM minimum", f"{stats['withVramSignal']}", "README lines or min_compute.yml miner block"],
    ["Cross-check: taostat registry entries", f"{sum(1 for t in taostat if t.get('hw_requirements'))}/{len(taostat)}", "Community-maintained hardware registry"],
    ["Cross-check: INFRANEX classifier", f"{len(viewC)} GPU classes", "Chain metadata + profiler, live via platform API"],
]
story.append(Spacer(1, 4))
story.append(make_table(["Pipeline stage", "Coverage", "Source / method"], meth_rows,
                        [0.34, 0.18, 0.48], num_cols=(1,)))
story.append(Spacer(1, 4))
story.append(Paragraph("Table 2: Data coverage at snapshot. Coverage is a floor - external docs and private "
                       "onboarding repos are invisible to repository scanning.", S['caption']))

# =====================================================================
# 3. THE VERIFIED GPU RANKING
# =====================================================================
story.extend(h1(3, "The Verified GPU Ranking", body(
    "Chart 1 shows the core result: every GPU model named in subnet repositories, with its mentions "
    "split by evidence tier. The A100 leads on raw presence - it is the default 'recommended GPU' "
    "that subnet teams write into min_compute.yml recommended_gpu fields and README requirement "
    "tables, and nearly all of its mentions are genuine miner-side requirements or recommendations "
    "rather than passing references. The RTX 4090 follows as the most-named consumer card: five "
    "subnets name it as a miner-side requirement or reference configuration, and unlike the A100 "
    "these are almost all 'what you actually need to compete' statements rather than aspirational "
    "recommendations - for example SN96 Verathos declares required=true with min_vram=24 and "
    "recommended_vram=48 anchored on the RTX 4090, and SN53 engy's runbook documents a production "
    "4x RTX 4090 miner.")))

story.extend(chart_block(f"{DIR}/charts/chart1-gpu-mentions.png", max_height=265))

story.append(body(
    "The datacenter tier tells a sharper story. The H100 and H200 each appear in four repositories, "
    "but their hard requirements are concentrated in exactly two high-value subnets: SN90 KubeTEE, "
    "whose miners must operate TEE-enabled GPU clusters of H100/H200/B200-class nodes "
    f"({sn90['minerEmissionTaoPerDay']:.0f} TAO/day of miner-side emissions), and SN40 Ralph, which calibrates its "
    "inference marketplace against H100 hardware. The B200/GB200 mentions follow the same pattern - "
    "next-generation cluster subnets rather than solo-miner targets. The A6000 deserves special "
    "mention: SN12 Compute Horde states it plainly ('requires A6000 - the only GPU supported now'), "
    "and SN64 Chutes - the single largest GPU mining opportunity in the network at "
    f"{sn64['minerEmissionTaoPerDay']:.0f} TAO/day of miner-side emissions - accepts A100, H100 and A6000-class "
    "hardware through its node-selector system with a per-GPU VRAM floor of 16 GB. In other words, "
    "the highest-value datacenter-GPU mining is marketplace-shaped: the subnet does not hand you a "
    "model requirement, it rents whatever VRAM-rich card you bring."))

story.extend(chart_block(f"{DIR}/charts/chart2-emission-weighted.png", max_height=235))

story.append(body(
    "Chart 2 re-weights the same evidence by money: the miner-side emissions of the subnets whose "
    "requirements name each card. The picture inverts the count ranking - the A6000 and the "
    "marketplace trio (A100/H100 via Chutes and KubeTEE) carry far more TAO per day than their "
    "subnet counts suggest, while the 4090's requirement footprint spans several mid-size but "
    "steady subnets. For an operator choosing hardware, this is the more honest chart: a 4090 "
    "opens five to six durable doors, while an A6000 or rented A100 opens the two largest but "
    "most operationally demanding ones."))

ev_rows = []
for v in viewA[:8]:
    best = v["evidence"][0] if v["evidence"] else None
    subs = ", ".join(f"SN{n}" for n in sorted(v["reqSubnets"])[:6])
    ev_rows.append([
        v["gpu"].replace("NVIDIA ", ""),
        subs + ("..." if v["reqCount"] > 6 else ""),
        short(best["quote"], 110) if best else "-",
    ])
story.append(Spacer(1, 4))
story.append(make_table(
    ["GPU", "Subnets with miner-side requirement", "Strongest evidence quote (from repo)"],
    ev_rows, [0.17, 0.25, 0.58], small=True))
story.append(Spacer(1, 4))
story.append(Paragraph("Table 3: Per-GPU requirement evidence with the strongest repository quote. Full quotes "
                       "for all 27 evidence-bearing subnets appear in Section 6.", S['caption']))

# =====================================================================
# 4. DEMAND BY VRAM CLASS
# =====================================================================
story.extend(h1(4, "Demand by VRAM Class", body(
    "Named models are only half the picture - many subnets specify a VRAM floor rather than a card, "
    "and VRAM is what actually gates which hardware you can deploy. We took the strongest explicit "
    "miner-side VRAM minimum available for each subnet (min_compute.yml miner block first, then "
    "requirement-context README lines), and bucketed the network into five hardware classes. The "
    f"result is unambiguous: the 24 GB class is the network's center of gravity with {cls24['subnets']} "
    f"subnets and {cls24['taoPerDay']:.0f} TAO/day ({usd_mo(cls24['taoPerDay']):,.0f} USD/month) of miner-side rewards - both the "
    "largest reward pool and a healthy number of distinct opportunities. The 8-12 GB entry class "
    f"actually hosts more subnets ({cls812['subnets']}, many CPU-optional or light-inference workloads), "
    f"but pays only {cls812['taoPerDay']:.0f} TAO/day - broad, cheap competition. The 16 GB middle class "
    "(4060 Ti 16G / 4080 / 5080 class) is small but lucrative at "
    f"{viewB[1]['taoPerDay']:.0f} TAO/day across {viewB[1]['subnets']} subnets, and the 80 GB+ datacenter class rounds "
    f"out the network with {viewB[-1]['subnets']} subnets worth {viewB[-1]['taoPerDay']:.0f} TAO/day.")))

story.extend(chart_block(f"{DIR}/charts/chart3-vram-classes.png", max_height=230))

bucket_rows = []
for c in viewB:
    bucket_rows.append([
        c["class"],
        str(c["subnets"]),
        f"{c['taoPerDay']:.1f}",
        f"${usd_mo(c['taoPerDay']):,.0f}",
        f"{c['taoPerDay'] / c['subnets']:.1f}",
    ])
story.append(Spacer(1, 4))
story.append(make_table(
    ["VRAM class", "Subnets", "Miner-side TAO/day", "USD/month", "TAO/day per subnet"],
    bucket_rows, [0.34, 0.12, 0.20, 0.18, 0.16], num_cols=(1, 2, 3, 4)))
story.append(Spacer(1, 4))
story.append(Paragraph("Table 4: VRAM-class demand. Subnet counts use the strongest explicit miner-side VRAM "
                       "minimum; 57 subnets publish no VRAM signal and are excluded from this view.", S['caption']))

story.append(body(
    "The per-subnet column of Table 4 is the practical one: the average 24 GB-class opportunity "
    "carries roughly 31 TAO/day of miner-side emissions versus 11 TAO/day in the 8-12 GB class - "
    "near triple the reward density per opportunity. The 32-48 GB middle (A6000 / L40S class) is "
    "conspicuously thin, only three subnets, because in Bittensor's economics you either run "
    "consumer-VRAM workloads or jump straight to marketplace datacenter hardware. Note also that "
    "VRAM minimums compound with other gates: several 80 GB+ subnets additionally require TEE-capable "
    "silicon or cluster-level Kubernetes, which is precisely why their high emissions have not been "
    "arbitraged away by an influx of lone miners."))

# =====================================================================
# 5. CROSS-CHECKS
# =====================================================================
tao_ok = sum(1 for t in taostat if t.get('hw_requirements'))
story.extend(h1(5, "Cross-Checks: Taostat Registry and the INFRANEX Classifier", body(
    "To make sure the repository scan is not an artifact of our own catalog, we compared it against "
    "two independent classification systems. The taostat community registry - the oldest public "
    f"hardware registry for Bittensor - carries hw_requirements entries for {tao_ok} of its {len(taostat)} tracked "
    "subnets, and those entries are dominated by links to the same min_compute.yml convention this "
    "report extracts directly, which corroborates both the convention's importance and our parsing "
    "of it. Where taostat carries free-text requirements they match our findings (for example its "
    "entry for the pretraining lineage points at the same min_compute.yml files our scan consumed "
    "directly). The registry's coverage ends at roughly the first 24 historically registered subnets, "
    "so it serves as a sanity check on the old guard rather than a full-network comparison.")))

story.append(body(
    "The second cross-check is INFRANEX's own subnet-requirements profiler - the same engine that "
    "powers the platform's DevOps Mining Journey. The classifier assigns each subnet a workload "
    "category and a representative GPU, interpolating a card when no explicit model is documented. "
    "Chart 4 shows its verdict across the network: 65 subnets are classified as runnable on a CPU "
    "VPS with no GPU at all, 26 as entry-GPU workloads (12 GB or less), and - most relevant here - "
    f"<b>17 subnets are mapped to the RTX 4090 24 GB class carrying {next(v for v in viewC if '4090' in v['gpu'])['taoPerDay']:.0f} TAO/day "
    "of miner-side emissions, with 12 more mapped to H100 80 GB</b>. The classifier's 4090-heavy view is "
    "deliberately representative rather than literal: when a subnet says '24 GB VRAM required' "
    "without naming a card, the profiler answers the operator's real question - 'what do I rent?' - "
    "with the market's default 24 GB card. That the classifier's largest GPU bucket independently "
    "lands on the same 24 GB class that our repo evidence ranks first is a strong consistency signal "
    "between two very different methodologies."))

story.extend(chart_block(f"{DIR}/charts/chart4-app-classifier.png", max_height=225))

story.append(body(
    "Two instructive disagreements are worth flagging. First, "
    f"SN122 CookingTAO - the top net-profit subnet on INFRANEX's opportunity board at roughly "
    f"${usd_mo(sn122['minerEmissionTaoPerDay']):,.0f}/month of miner-side emissions - publishes no public README at "
    "all: its mining client is distributed through the team's private onboarding, and the profiler "
    f"classifies it as '{sn122['appGpuRequired'] or 'GPU required'}' from chain metadata and category signals alone. "
    "That is exactly the kind of subnet where repository evidence goes dark and profiler inference "
    "has to carry the load. Second, SN64 Chutes is classified conservatively as an H100-class "
    "marketplace, while its repository in fact accepts anything from an A6000 (48 GB) upward through "
    "H100/H200/B200 - a reminder that classifier labels are entry heuristics, and the underlying "
    "repo text (Section 6) is the authoritative record."))

# =====================================================================
# 6. PER-SUBNET EVIDENCE MAP
# =====================================================================
story.extend(h1(6, "The Per-Subnet Evidence Map", body(
    "This section is the audit trail. Every subnet whose repository names a specific GPU model is "
    "listed below with its strongest evidence quote, the file the quote came from, and its tier "
    "(1 = explicit requirement, 2 = miner-side supported/declared, 3 = generic mention including "
    "validator docs and benchmark tables). Quotes are reproduced verbatim from the repositories, so "
    "any figure in this report can be traced back to its source line. Subnets are sorted by "
    "miner-side emissions descending, because that is the order in which a miner evaluating where "
    "to deploy will encounter them.")))

tier_lbl = {1: "1 - requirement", 2: "2 - supported", 3: "3 - mention"}
ment = [s for s in evid if s["gpus"]]
ment.sort(key=lambda s: -(s["minerEmissionTaoPerDay"] or 0))
ev_all = []
for s in ment:
    g = s["gpus"][0]
    ev_all.append([
        f"SN{s['netuid']}",
        s["name"][:20],
        g["gpu"].replace("NVIDIA ", ""),
        tier_lbl.get(g.get("tier", 3), "3"),
        short(g["quote"], 120),
        f"{(s['minerEmissionTaoPerDay'] or 0):.1f}",
    ])
story.append(Spacer(1, 4))
story.append(make_table(
    ["Subnet", "Name", "GPU named", "Tier", "Verbatim evidence quote (strongest)", "Miner TAO/d"],
    ev_all, [0.075, 0.135, 0.135, 0.105, 0.44, 0.11], small=True, num_cols=(5,)))
story.append(Spacer(1, 4))
story.append(Paragraph(f"Table 5: All {len(ev_all)} subnets whose repositories name a specific GPU model, sorted by "
                       "miner-side emissions. Where a repository names several GPUs the strongest-tier one is shown; "
                       "full per-subnet detail is in the accompanying JSON dataset.", S['caption']))

story.append(h2("6.1 Subnets where repository evidence is absent"))
story.append(body(
    "For completeness, the following higher-emission subnets expose no readable repository README "
    "and therefore cannot contribute evidence here: SN0 (root network - not minable), SN120 Affine "
    "(134.0 TAO/day, repository exists but ships no README), SN95 Actual (105.8), SN97 Albedo (59.4), "
    "SN110 Green Compute (31.9) and SN122 CookingTAO (11.5, private mining client). A further group - "
    "SN16, SN30, SN31, SN42, SN73, SN87, SN99, SN109, SN112 - have malformed or parked chain "
    "identities ('0x' placeholders or dead links) and are effectively dormant. None of these change "
    "the ranking conclusions, but SN120 and SN95 in particular are large enough that their true "
    "requirements deserve a manual check through their official documentation before committing "
    "hardware, and the INFRANEX profiler classifications quoted in Section 5 are the best "
    "standing estimates for them."))

# =====================================================================
# 7. WHAT THIS MEANS FOR GPU MINERS
# =====================================================================
story.extend(h1(7, "What This Means for GPU Miners", body(
    "If you own or plan to acquire a single consumer GPU for Bittensor mining, the evidence points "
    "to the <b>RTX 4090 (24 GB)</b> as the most versatile card in the network: it is the named "
    "reference card in five subnets' miner requirements, it satisfies the entire 24 GB VRAM class "
    f"(16 subnets, {cls24['taoPerDay']:.0f} TAO/day of miner-side rewards), and it clears the 16 GB class "
    f"({viewB[1]['subnets']} subnets) as well. The RTX 5090 appears as an accepted alternative where noted "
    "(SN108), but subnets do not yet require it anywhere, so paying the 5090 premium purely for "
    "Bittensor is not supported by today's evidence. Cards below 16 GB are viable in the 8-12 GB "
    "class but face the thinnest reward density per subnet, and several of those subnets are "
    "CPU-optional, meaning GPU-less competitors can dilute them.")))

story.append(body(
    "If you rent datacenter capacity instead, target the two marketplace-shaped giants: SN64 Chutes "
    f"({sn64['minerEmissionTaoPerDay']:.0f} TAO/day of miner-side emissions, A6000/H100/H200 accepted with 16 GB "
    "per-GPU minimums) and SN90 KubeTEE (H100/H200/B200 TEE clusters), plus the nine A100-anchored "
    "subnets from Table 3. The H200 question deserves a direct answer, since it motivated this "
    "study: <b>the H200 is neither required nor forbidden anywhere on its own merits</b> - it appears "
    "only inside KubeTEE's H100-or-newer cluster menu and as a passing option elsewhere, so an H200 "
    "purchase justified by Bittensor alone would rest on one subnet's co-equal option. An H100 or "
    "A100 rental unlocks strictly more subnets today at lower cost."))

strategy_rows = [
    ["RTX 4090 / 24 GB class", "iota (SN9), ItsAI (SN32), engy (SN53), Yanez (SN54), Verathos (SN96)", "24 GB class: 16 subnets, 500.6 TAO/d"],
    ["RTX 5090", "SN108 plus any 24 GB-class subnet", "Accepted in 2 repos; required by none"],
    ["A6000 48 GB", "Compute Horde (SN12), Chutes (SN64)", "Chutes alone carries 92.5 TAO/d"],
    ["A100 / H100 80 GB", "Chutes (SN64), KubeTEE (SN90), + 9 A100-anchored subnets", "80 GB+ class: 14 subnets, 186.5 TAO/d"],
    ["H200", "KubeTEE cluster menu only (with H100/B200)", "No solo-miner requirement anywhere"],
]
story.append(Spacer(1, 4))
story.append(make_table(
    ["Your hardware", "Top target subnets from the evidence", "Reward pool unlocked"],
    strategy_rows, [0.22, 0.44, 0.34], small=True))
story.append(Spacer(1, 4))
story.append(Paragraph("Table 6: Hardware-to-subnet strategy map derived from the verified evidence.", S['caption']))

story.append(body(
    "Operationally, fold this research into the INFRANEX Mining Journey: in step 1 (choose what to "
    "mine) the Opportunities board already ranks subnets by your profitability target; use Section "
    "6's evidence table to check the named-GPU requirement before step 2 (rent a GPU host), and let "
    "the DevOps Engine's per-subnet requirements profiler pull the authoritative, freshly-cached "
    "specification for your chosen subnet before you commit to a rental. The profiler's per-subnet "
    "pull is the live counterpart of this report's snapshot - emissions, prices and requirements all "
    "drift week to week, and the ten-step validation pipeline will verify the host you actually "
    "rented against the subnet's real driver, CUDA and VRAM gates before any miner is installed."))

# =====================================================================
# 8. COVERAGE LIMITS AND CAVEATS
# =====================================================================
story.extend(h1(8, "Coverage Limits and Caveats", body(
    "Four limitations bound these conclusions, and none of them is silent - each can be checked or "
    "re-measured. First, coverage: 108 of 129 READMEs is strong by count, but the unreadable tail "
    f"holds {unres_share:.0f}% of miner-side emissions, concentrated in SN0, SN120, SN95 and SN97; any claim "
    "about those specific subnets in this report is explicitly marked as inference. Second, "
    "documentation culture: repository READMEs undersell GPU requirements because teams maintain "
    "setup guides on docs sites, Discord and private onboarding repos; the tier system exists "
    "precisely so that soft signals are never presented as hard requirements, and the classifier "
    "cross-check in Section 5 exists so that silence in repositories is not mistaken for absence "
    "of GPUs.")))

story.append(body(
    "Third, extraction judgment: regex catalogs cannot perfectly judge intent, which is why every "
    "claim ships with its verbatim quote - the strongest quotes were manually reviewed during "
    "analysis, and borderline cases (benchmark tables, marketplace node-selectors, miner-declared "
    "hardware) are tiered conservatively; where a tier genuinely matters to a decision, read the "
    "quote, not the tier. Fourth, time: this is a snapshot at block "
    f"{dset['blockNumber']:,} (September 10, 2026, TAO at ${TAO_P:.2f}); subnet requirements change with "
    "releases, emissions drift daily, and the RTX 5090's near-absence from requirements will "
    "presumably age as the installed base grows. Re-running the pipeline is a five-minute exercise "
    "on the INFRANEX platform - treat this document as the baseline that future snapshots are "
    "diffed against, not as a permanent truth."))

# =====================================================================
# BUILD + MERGE COVER
# =====================================================================
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print(f"body built: {OUT_BODY}")

from pypdf import PdfReader, PdfWriter

A4_W, A4_H = 595.28, 841.89

def normalize_page_to_a4(page):
    box = page.mediabox
    w, h = float(box.width), float(box.height)
    if abs(w - A4_W) > 0.1 or abs(h - A4_H) > 0.1:
        page.scale_to(A4_W, A4_H)
    return page

FINAL = "/home/z/my-project/download/infranex-gpu-research-2026-09-10.pdf"
os.makedirs(os.path.dirname(FINAL), exist_ok=True)
writer = PdfWriter()
writer.add_page(normalize_page_to_a4(PdfReader(f"{DIR}/cover.pdf").pages[0]))
for page in PdfReader(OUT_BODY).pages:
    writer.add_page(normalize_page_to_a4(page))
writer.add_metadata({
    '/Title': DOC_TITLE,
    '/Author': 'Z.ai',
    '/Creator': 'Z.ai',
    '/Subject': 'GPU requirements across Bittensor subnets, mined from subnet repositories',
})
with open(FINAL, 'wb') as f:
    writer.write(f)
print(f"final: {FINAL} ({len(PdfReader(FINAL).pages)} pages)")
