#!/usr/bin/env python3
"""
subnet-ui-1: generate src/lib/infranex/subnet-jobs-seed.ts from the synthesis
batches (scripts/subnet-info-synth/batch-{1..4}.json).
"""
import json, os

BASE = "/home/z/my-project"
SYN = os.path.join(BASE, "scripts", "subnet-info-synth")
OUT = os.path.join(BASE, "src", "lib", "infranex", "subnet-jobs-seed.ts")

entries = []
for b in (1, 2, 3, 4):
    entries.extend(json.load(open(os.path.join(SYN, f"batch-{b}.json"))))
entries.sort(key=lambda e: e["netuid"])
assert len(entries) == 129, len(entries)

def s(x):
    """TS-safe string literal."""
    return json.dumps(str(x), ensure_ascii=False)

lines = []
lines.append("// AUTO-GENERATED by scripts/gen-subnet-jobs-seed.py — do not edit by hand.")
lines.append("// Source: 129-subnet capability synthesis (subnet-info-1) — GitHub README")
lines.append("// miner/validator sections (96), web research (16), chain identity only (17).")
lines.append("// Regenerate: python3 scripts/gen-subnet-jobs-seed.py")
lines.append("")
lines.append("export interface SubnetJobSeedEntry {")
lines.append("  name: string;")
lines.append("  category: string;")
lines.append("  /** Short tag: what KIND of work the miner performs. */")
lines.append("  minerWorkType: string;")
lines.append("  /** What problem the subnet solves / service it provides. */")
lines.append("  whatItDoes: string;")
lines.append("  /** Concrete miner job: hardware, tasks received, work performed. */")
lines.append("  whatMinerDoes: string;")
lines.append("  /** How validators score/rank miners. */")
lines.append("  whatValidatorDoes: string;")
lines.append("  /** Short phrase: what determines rewards. */")
lines.append("  rewardBasis: string;")
lines.append('  /** Evidence depth: "readme" (verified from repo) | "research" | "chain-only". */')
lines.append("  confidence: \"readme\" | \"research\" | \"chain-only\";")
lines.append("  /** Repo slug, \"web\", or \"chain\". */")
lines.append("  source: string;")
lines.append("}")
lines.append("")
lines.append("export const SUBNET_JOBS_SEED: Record<number, SubnetJobSeedEntry> = {")
for e in entries:
    name = e.get("name") or f"Subnet {e['netuid']}"
    lines.append(f"  {e['netuid']}: {{")
    lines.append(f"    name: {s(name)},")
    lines.append(f"    category: {s(e.get('category') or 'Other')},")
    lines.append(f"    minerWorkType: {s(e.get('minerWorkType') or '')},")
    lines.append(f"    whatItDoes: {s(e.get('whatItDoes') or '')},")
    lines.append(f"    whatMinerDoes: {s(e.get('whatMinerDoes') or '')},")
    lines.append(f"    whatValidatorDoes: {s(e.get('whatValidatorDoes') or '')},")
    lines.append(f"    rewardBasis: {s(e.get('rewardBasis') or '')},")
    lines.append(f"    confidence: {s(e.get('confidence') or 'chain-only')},")
    lines.append(f"    source: {s(e.get('source') or 'chain')},")
    lines.append("  },")
lines.append("};")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} ({os.path.getsize(OUT)//1024} KB, {len(entries)} entries)")
