#!/usr/bin/env python3
"""Generate src/lib/infranex/compat-seed.ts from the subnet hosting audit.

Reads tool-results/classified.json (produced by scripts/classify-subnets.py)
and emits a TypeScript seed module with a per-subnet GPU hosting compat tier,
note, evidence quote and source repo.
"""
import json

CLASSIFIED = "tool-results/classified.json"
OUT = "src/lib/infranex/compat-seed.ts"

TIER_MAP = {
    "BARE_METAL_TEE": ("bare-metal-only", "audit"),
    "TEE": ("tee-required", "audit"),
    "PROVIDER_GUIDES": ("provider-friendly", "audit"),
    "GPU_FLEXIBLE": ("gpu-flexible", "readme"),
    "GPU_FLEXIBLE_INFERRED": ("gpu-flexible", "inferred"),
    "CPU": ("cpu-only", "readme"),
    "LIKELY_NON_GPU": ("cpu-only", "inferred"),
    "UNSPECIFIED": ("unclear", "audit"),
    "REPO_EMPTY": ("unclear", "audit"),
    "NO_REPO": ("no-repo", "audit"),
    "PARKED": ("parked", "audit"),
}

# Hand-written evidence quotes for the tiers where exact wording matters.
EVIDENCE = {
    64: (
        "ALL servers must be bare metal/VM, meaning it will not work on Runpod, Vast, etc., and we do not currently support shared or dynamic IPs - the IPs must be unique, static, and provide a 1:1 port mapping.",
        "chutesai/chutes-miner README",
    ),
    4: (
        "Bare metal access for secure AI workloads ... Targon leverages Trusted Execution Environment and Confidential Compute to secure the entire stack (NVIDIA CC mode).",
        "manifold-inc/targon README",
    ),
    51: (
        "neurons/executor - the agent installed on a GPU machine: exposes the machine to its miner's validators, runs the container inside an Intel TDX TEE so neither operators nor host machines see buyer content or miners' data.",
        "Datura-ai/lium-io README",
    ),
    28: (
        "Miner must run inside an Intel TDX TEE (Phala Cloud CVM) so neither operators nor host machines see buyer content.",
        "SayGM subnet README (curated audit)",
    ),
    90: (
        "KubeTEE AI turns decentralized GPU clusters into a confidential factory - TEE-attested Kubernetes (Intel TDX + NVIDIA CC, Kata+CoCo, 8-GPU passthrough).",
        "KubeTEE-AI/kubetee-subnet README",
    ),
    76: (
        "Ormas neither blocks nor supports that: there is no compatibility promise beyond the published protocol - hosted/gateway setups are explicitly unsupported.",
        "heroncovelabs/ormas-subnet README",
    ),
    33: (
        "Get Running Quickly with the Docker Image! ... Get a miner Running on Runpod - the README ships an official RunPod setup section.",
        "afterpartyai/bittensor-conversation-genome-project README",
    ),
    12: (
        "Compute Horde operates as a compute rental layer - miners run worker nodes that the network rents out.",
        "backend-developers-ltd/ComputeHorde README",
    ),
}

rows = json.load(open(CLASSIFIED))
entries = []
for r in rows:
    n = int(r["netuid"])
    if n == 0:
        continue
    cls = r["cls"]
    tier, source = TIER_MAP[cls]
    note = r["why"]
    repo = r.get("repo")
    quote, ev_src = EVIDENCE.get(n, (None, None))
    entries.append({
        "netuid": n,
        "tier": tier,
        "source": source,
        "note": note,
        "quote": quote,
        "evidenceSource": ev_src or (repo or None),
    })

entries.sort(key=lambda e: e["netuid"])

lines = [
    '// AUTO-GENERATED by scripts/gen-compat-seed.py - do not edit by hand.',
    '// Source: full-subnet README hosting audit (128 subnets, evidence quotes',
    '// captured from each repo). Regenerate after re-running the audit.',
    '',
    'export interface CompatSeedEntry {',
    '  tier:',
    '    | "bare-metal-only"',
    '    | "tee-required"',
    '    | "provider-friendly"',
    '    | "gpu-flexible"',
    '    | "cpu-only"',
    '    | "unclear"',
    '    | "no-repo"',
    '    | "parked";',
    '  /** "audit" tiers carry hand-verified evidence; "readme" tiers come from',
    '   *  scraped README keyword evidence; "inferred" tiers are heuristic. */',
    '  source: "audit" | "readme" | "inferred";',
    '  /** One-line audit finding. */',
    '  note: string;',
    '  /** Verbatim quote from the subnet README (strict tiers). */',
    '  quote?: string;',
    '  /** Repo / doc the quote came from. */',
    '  evidenceSource?: string;',
    '}',
    '',
    'export const COMPAT_SEED: Record<number, CompatSeedEntry> = {',
]
for e in entries:
    note = e["note"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'  {e["netuid"]}: {{ tier: "{e["tier"]}", source: "{e["source"]}", note: "{note}",')
    if e["quote"]:
        q = e["quote"].replace("\\", "\\\\").replace('"', '\\"')
        src = (e["evidenceSource"] or "").replace('"', '\\"')
        lines.append(f'    quote: "{q}", evidenceSource: "{src}"')
    lines.append('  },')
lines.append('};')
lines.append('')

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(entries)} entries")
from collections import Counter
print(Counter(e["tier"] for e in entries))
